version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://i202424:waleedsufi123@task5.njfplee.mongodb.net/user?retryWrites=true&w=majority&appName=Task5
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
