version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://i202424:waleedsufi123@task5.njfplee.mongodb.net/user?retryWrites=true&w=majority&appName=Task5
  frontend:
    build: ./frontend/user-data-form # Ensure this path points to your React app's Dockerfile
    ports:
      - "80:3000" # Map port 3000 in the container to port 80 on the host
    depends_on:
      - backend
